/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Unidad } from './Unidad';
import {
    UnidadFromJSON,
    UnidadFromJSONTyped,
    UnidadToJSON,
    UnidadToJSONTyped,
} from './Unidad';

/**
 * 
 * @export
 * @interface Cobros
 */
export interface Cobros {
    /**
     * 
     * @type {number}
     * @memberof Cobros
     */
    id?: number;
    /**
     * 
     * @type {Unidad}
     * @memberof Cobros
     */
    unidad?: Unidad;
    /**
     * 
     * @type {number}
     * @memberof Cobros
     */
    tarifaUnica?: number;
    /**
     * 
     * @type {number}
     * @memberof Cobros
     */
    cuotaAsociacion?: number;
    /**
     * 
     * @type {number}
     * @memberof Cobros
     */
    fondoEstrella?: number;
    /**
     * 
     * @type {number}
     * @memberof Cobros
     */
    dias?: number;
    /**
     * 
     * @type {Date}
     * @memberof Cobros
     */
    fechaTraslado?: Date;
}

/**
 * Check if a given object implements the Cobros interface.
 */
export function instanceOfCobros(value: object): value is Cobros {
    return true;
}

export function CobrosFromJSON(json: any): Cobros {
    return CobrosFromJSONTyped(json, false);
}

export function CobrosFromJSONTyped(json: any, ignoreDiscriminator: boolean): Cobros {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'unidad': json['unidad'] == null ? undefined : UnidadFromJSON(json['unidad']),
        'tarifaUnica': json['tarifaUnica'] == null ? undefined : json['tarifaUnica'],
        'cuotaAsociacion': json['cuotaAsociacion'] == null ? undefined : json['cuotaAsociacion'],
        'fondoEstrella': json['fondoEstrella'] == null ? undefined : json['fondoEstrella'],
        'dias': json['dias'] == null ? undefined : json['dias'],
        'fechaTraslado': json['fechaTraslado'] == null ? undefined : (new Date(json['fechaTraslado'])),
    };
}

export function CobrosToJSON(json: any): Cobros {
    return CobrosToJSONTyped(json, false);
}

export function CobrosToJSONTyped(value?: Cobros | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'unidad': UnidadToJSON(value['unidad']),
        'tarifaUnica': value['tarifaUnica'],
        'cuotaAsociacion': value['cuotaAsociacion'],
        'fondoEstrella': value['fondoEstrella'],
        'dias': value['dias'],
        'fechaTraslado': value['fechaTraslado'] == null ? undefined : ((value['fechaTraslado']).toISOString().substring(0,10)),
    };
}

