/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CobroDTO
 */
export interface CobroDTO {
    /**
     * 
     * @type {number}
     * @memberof CobroDTO
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof CobroDTO
     */
    unidadId?: number;
    /**
     * 
     * @type {number}
     * @memberof CobroDTO
     */
    tarifaUnica?: number;
    /**
     * 
     * @type {number}
     * @memberof CobroDTO
     */
    cuotaAsociacion?: number;
    /**
     * 
     * @type {number}
     * @memberof CobroDTO
     */
    fondoEstrella?: number;
    /**
     * 
     * @type {number}
     * @memberof CobroDTO
     */
    dias?: number;
    /**
     * 
     * @type {string}
     * @memberof CobroDTO
     */
    fechaTraslado?: string;
}

/**
 * Check if a given object implements the CobroDTO interface.
 */
export function instanceOfCobroDTO(value: object): value is CobroDTO {
    return true;
}

export function CobroDTOFromJSON(json: any): CobroDTO {
    return CobroDTOFromJSONTyped(json, false);
}

export function CobroDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): CobroDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'unidadId': json['unidadId'] == null ? undefined : json['unidadId'],
        'tarifaUnica': json['tarifaUnica'] == null ? undefined : json['tarifaUnica'],
        'cuotaAsociacion': json['cuotaAsociacion'] == null ? undefined : json['cuotaAsociacion'],
        'fondoEstrella': json['fondoEstrella'] == null ? undefined : json['fondoEstrella'],
        'dias': json['dias'] == null ? undefined : json['dias'],
        'fechaTraslado': json['fechaTraslado'] == null ? undefined : json['fechaTraslado'],
    };
}

export function CobroDTOToJSON(json: any): CobroDTO {
    return CobroDTOToJSONTyped(json, false);
}

export function CobroDTOToJSONTyped(value?: CobroDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'unidadId': value['unidadId'],
        'tarifaUnica': value['tarifaUnica'],
        'cuotaAsociacion': value['cuotaAsociacion'],
        'fondoEstrella': value['fondoEstrella'],
        'dias': value['dias'],
        'fechaTraslado': value['fechaTraslado'],
    };
}

