/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CrearUnidadRequest
 */
export interface CrearUnidadRequest {
    /**
     * 
     * @type {string}
     * @memberof CrearUnidadRequest
     */
    noSerie?: string;
    /**
     * 
     * @type {string}
     * @memberof CrearUnidadRequest
     */
    comentario?: string;
    /**
     * 
     * @type {string}
     * @memberof CrearUnidadRequest
     */
    origen?: string;
    /**
     * 
     * @type {string}
     * @memberof CrearUnidadRequest
     */
    debisFecha?: string;
    /**
     * 
     * @type {string}
     * @memberof CrearUnidadRequest
     */
    reportadoA?: string;
    /**
     * 
     * @type {string}
     * @memberof CrearUnidadRequest
     */
    pagoDistribuidora?: string;
    /**
     * 
     * @type {number}
     * @memberof CrearUnidadRequest
     */
    valorUnidad?: number;
    /**
     * 
     * @type {number}
     * @memberof CrearUnidadRequest
     */
    modeloId?: number;
    /**
     * 
     * @type {number}
     * @memberof CrearUnidadRequest
     */
    distribuidorId?: number;
}

/**
 * Check if a given object implements the CrearUnidadRequest interface.
 */
export function instanceOfCrearUnidadRequest(value: object): value is CrearUnidadRequest {
    return true;
}

export function CrearUnidadRequestFromJSON(json: any): CrearUnidadRequest {
    return CrearUnidadRequestFromJSONTyped(json, false);
}

export function CrearUnidadRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CrearUnidadRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'noSerie': json['noSerie'] == null ? undefined : json['noSerie'],
        'comentario': json['comentario'] == null ? undefined : json['comentario'],
        'origen': json['origen'] == null ? undefined : json['origen'],
        'debisFecha': json['debisFecha'] == null ? undefined : json['debisFecha'],
        'reportadoA': json['reportadoA'] == null ? undefined : json['reportadoA'],
        'pagoDistribuidora': json['pagoDistribuidora'] == null ? undefined : json['pagoDistribuidora'],
        'valorUnidad': json['valorUnidad'] == null ? undefined : json['valorUnidad'],
        'modeloId': json['modeloId'] == null ? undefined : json['modeloId'],
        'distribuidorId': json['distribuidorId'] == null ? undefined : json['distribuidorId'],
    };
}

export function CrearUnidadRequestToJSON(json: any): CrearUnidadRequest {
    return CrearUnidadRequestToJSONTyped(json, false);
}

export function CrearUnidadRequestToJSONTyped(value?: CrearUnidadRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'noSerie': value['noSerie'],
        'comentario': value['comentario'],
        'origen': value['origen'],
        'debisFecha': value['debisFecha'],
        'reportadoA': value['reportadoA'],
        'pagoDistribuidora': value['pagoDistribuidora'],
        'valorUnidad': value['valorUnidad'],
        'modeloId': value['modeloId'],
        'distribuidorId': value['distribuidorId'],
    };
}

