/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CrearModeloRequest
 */
export interface CrearModeloRequest {
    /**
     * 
     * @type {string}
     * @memberof CrearModeloRequest
     */
    nombre?: string;
    /**
     * 
     * @type {string}
     * @memberof CrearModeloRequest
     */
    uso?: string;
}

/**
 * Check if a given object implements the CrearModeloRequest interface.
 */
export function instanceOfCrearModeloRequest(value: object): value is CrearModeloRequest {
    return true;
}

export function CrearModeloRequestFromJSON(json: any): CrearModeloRequest {
    return CrearModeloRequestFromJSONTyped(json, false);
}

export function CrearModeloRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CrearModeloRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'nombre': json['nombre'] == null ? undefined : json['nombre'],
        'uso': json['uso'] == null ? undefined : json['uso'],
    };
}

export function CrearModeloRequestToJSON(json: any): CrearModeloRequest {
    return CrearModeloRequestToJSONTyped(json, false);
}

export function CrearModeloRequestToJSONTyped(value?: CrearModeloRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'nombre': value['nombre'],
        'uso': value['uso'],
    };
}

