/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Unidad } from './Unidad';
import {
    UnidadFromJSON,
    UnidadFromJSONTyped,
    UnidadToJSON,
    UnidadToJSONTyped,
} from './Unidad';

/**
 * 
 * @export
 * @interface Distribuidor
 */
export interface Distribuidor {
    /**
     * 
     * @type {number}
     * @memberof Distribuidor
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof Distribuidor
     */
    nombreDistribuidora?: string;
    /**
     * 
     * @type {string}
     * @memberof Distribuidor
     */
    claveDistribuidora?: string;
    /**
     * 
     * @type {string}
     * @memberof Distribuidor
     */
    contacto?: string;
    /**
     * 
     * @type {number}
     * @memberof Distribuidor
     */
    telefono?: number;
    /**
     * 
     * @type {number}
     * @memberof Distribuidor
     */
    extension?: number;
    /**
     * 
     * @type {string}
     * @memberof Distribuidor
     */
    correo?: string;
    /**
     * 
     * @type {string}
     * @memberof Distribuidor
     */
    sucursal?: string;
    /**
     * 
     * @type {Array<Unidad>}
     * @memberof Distribuidor
     */
    unidades?: Array<Unidad>;
}

/**
 * Check if a given object implements the Distribuidor interface.
 */
export function instanceOfDistribuidor(value: object): value is Distribuidor {
    return true;
}

export function DistribuidorFromJSON(json: any): Distribuidor {
    return DistribuidorFromJSONTyped(json, false);
}

export function DistribuidorFromJSONTyped(json: any, ignoreDiscriminator: boolean): Distribuidor {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'nombreDistribuidora': json['nombreDistribuidora'] == null ? undefined : json['nombreDistribuidora'],
        'claveDistribuidora': json['claveDistribuidora'] == null ? undefined : json['claveDistribuidora'],
        'contacto': json['contacto'] == null ? undefined : json['contacto'],
        'telefono': json['telefono'] == null ? undefined : json['telefono'],
        'extension': json['extension'] == null ? undefined : json['extension'],
        'correo': json['correo'] == null ? undefined : json['correo'],
        'sucursal': json['sucursal'] == null ? undefined : json['sucursal'],
        'unidades': json['unidades'] == null ? undefined : ((json['unidades'] as Array<any>).map(UnidadFromJSON)),
    };
}

export function DistribuidorToJSON(json: any): Distribuidor {
    return DistribuidorToJSONTyped(json, false);
}

export function DistribuidorToJSONTyped(value?: Distribuidor | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'nombreDistribuidora': value['nombreDistribuidora'],
        'claveDistribuidora': value['claveDistribuidora'],
        'contacto': value['contacto'],
        'telefono': value['telefono'],
        'extension': value['extension'],
        'correo': value['correo'],
        'sucursal': value['sucursal'],
        'unidades': value['unidades'] == null ? undefined : ((value['unidades'] as Array<any>).map(UnidadToJSON)),
    };
}

