/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DistribuidoraInfoDTO
 */
export interface DistribuidoraInfoDTO {
    /**
     * 
     * @type {number}
     * @memberof DistribuidoraInfoDTO
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof DistribuidoraInfoDTO
     */
    nombreDistribuidora?: string;
    /**
     * 
     * @type {string}
     * @memberof DistribuidoraInfoDTO
     */
    claveDistribuidora?: string;
}

/**
 * Check if a given object implements the DistribuidoraInfoDTO interface.
 */
export function instanceOfDistribuidoraInfoDTO(value: object): value is DistribuidoraInfoDTO {
    return true;
}

export function DistribuidoraInfoDTOFromJSON(json: any): DistribuidoraInfoDTO {
    return DistribuidoraInfoDTOFromJSONTyped(json, false);
}

export function DistribuidoraInfoDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): DistribuidoraInfoDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'nombreDistribuidora': json['nombreDistribuidora'] == null ? undefined : json['nombreDistribuidora'],
        'claveDistribuidora': json['claveDistribuidora'] == null ? undefined : json['claveDistribuidora'],
    };
}

export function DistribuidoraInfoDTOToJSON(json: any): DistribuidoraInfoDTO {
    return DistribuidoraInfoDTOToJSONTyped(json, false);
}

export function DistribuidoraInfoDTOToJSONTyped(value?: DistribuidoraInfoDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'nombreDistribuidora': value['nombreDistribuidora'],
        'claveDistribuidora': value['claveDistribuidora'],
    };
}

