/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ModeloDTO
 */
export interface ModeloDTO {
    /**
     * 
     * @type {number}
     * @memberof ModeloDTO
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof ModeloDTO
     */
    nombre?: string;
    /**
     * 
     * @type {string}
     * @memberof ModeloDTO
     */
    uso?: string;
}

/**
 * Check if a given object implements the ModeloDTO interface.
 */
export function instanceOfModeloDTO(value: object): value is ModeloDTO {
    return true;
}

export function ModeloDTOFromJSON(json: any): ModeloDTO {
    return ModeloDTOFromJSONTyped(json, false);
}

export function ModeloDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModeloDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'nombre': json['nombre'] == null ? undefined : json['nombre'],
        'uso': json['uso'] == null ? undefined : json['uso'],
    };
}

export function ModeloDTOToJSON(json: any): ModeloDTO {
    return ModeloDTOToJSONTyped(json, false);
}

export function ModeloDTOToJSONTyped(value?: ModeloDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'nombre': value['nombre'],
        'uso': value['uso'],
    };
}

