/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SeguroDTO
 */
export interface SeguroDTO {
    /**
     * 
     * @type {number}
     * @memberof SeguroDTO
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof SeguroDTO
     */
    factura?: string;
    /**
     * 
     * @type {number}
     * @memberof SeguroDTO
     */
    valorSeguro?: number;
    /**
     * 
     * @type {number}
     * @memberof SeguroDTO
     */
    seguroDistribuidor?: number;
    /**
     * 
     * @type {number}
     * @memberof SeguroDTO
     */
    unidadId?: number;
    /**
     * 
     * @type {number}
     * @memberof SeguroDTO
     */
    distribuidorId?: number;
}

/**
 * Check if a given object implements the SeguroDTO interface.
 */
export function instanceOfSeguroDTO(value: object): value is SeguroDTO {
    return true;
}

export function SeguroDTOFromJSON(json: any): SeguroDTO {
    return SeguroDTOFromJSONTyped(json, false);
}

export function SeguroDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): SeguroDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'factura': json['factura'] == null ? undefined : json['factura'],
        'valorSeguro': json['valorSeguro'] == null ? undefined : json['valorSeguro'],
        'seguroDistribuidor': json['seguroDistribuidor'] == null ? undefined : json['seguroDistribuidor'],
        'unidadId': json['unidadId'] == null ? undefined : json['unidadId'],
        'distribuidorId': json['distribuidorId'] == null ? undefined : json['distribuidorId'],
    };
}

export function SeguroDTOToJSON(json: any): SeguroDTO {
    return SeguroDTOToJSONTyped(json, false);
}

export function SeguroDTOToJSONTyped(value?: SeguroDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'factura': value['factura'],
        'valorSeguro': value['valorSeguro'],
        'seguroDistribuidor': value['seguroDistribuidor'],
        'unidadId': value['unidadId'],
        'distribuidorId': value['distribuidorId'],
    };
}

