/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Distribuidor } from './Distribuidor';
import {
    DistribuidorFromJSON,
    DistribuidorFromJSONTyped,
    DistribuidorToJSON,
    DistribuidorToJSONTyped,
} from './Distribuidor';
import type { Unidad } from './Unidad';
import {
    UnidadFromJSON,
    UnidadFromJSONTyped,
    UnidadToJSON,
    UnidadToJSONTyped,
} from './Unidad';

/**
 * 
 * @export
 * @interface Seguro
 */
export interface Seguro {
    /**
     * 
     * @type {number}
     * @memberof Seguro
     */
    id?: number;
    /**
     * 
     * @type {Distribuidor}
     * @memberof Seguro
     */
    distribuidor?: Distribuidor;
    /**
     * 
     * @type {Unidad}
     * @memberof Seguro
     */
    unidad?: Unidad;
    /**
     * 
     * @type {string}
     * @memberof Seguro
     */
    factura?: string;
    /**
     * 
     * @type {number}
     * @memberof Seguro
     */
    valorSeguro?: number;
    /**
     * 
     * @type {number}
     * @memberof Seguro
     */
    seguroDistribuidor?: number;
    /**
     * 
     * @type {number}
     * @memberof Seguro
     */
    cuotaSeguro?: number;
}

/**
 * Check if a given object implements the Seguro interface.
 */
export function instanceOfSeguro(value: object): value is Seguro {
    return true;
}

export function SeguroFromJSON(json: any): Seguro {
    return SeguroFromJSONTyped(json, false);
}

export function SeguroFromJSONTyped(json: any, ignoreDiscriminator: boolean): Seguro {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'distribuidor': json['distribuidor'] == null ? undefined : DistribuidorFromJSON(json['distribuidor']),
        'unidad': json['unidad'] == null ? undefined : UnidadFromJSON(json['unidad']),
        'factura': json['factura'] == null ? undefined : json['factura'],
        'valorSeguro': json['valorSeguro'] == null ? undefined : json['valorSeguro'],
        'seguroDistribuidor': json['seguroDistribuidor'] == null ? undefined : json['seguroDistribuidor'],
        'cuotaSeguro': json['cuotaSeguro'] == null ? undefined : json['cuotaSeguro'],
    };
}

export function SeguroToJSON(json: any): Seguro {
    return SeguroToJSONTyped(json, false);
}

export function SeguroToJSONTyped(value?: Seguro | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'distribuidor': DistribuidorToJSON(value['distribuidor']),
        'unidad': UnidadToJSON(value['unidad']),
        'factura': value['factura'],
        'valorSeguro': value['valorSeguro'],
        'seguroDistribuidor': value['seguroDistribuidor'],
        'cuotaSeguro': value['cuotaSeguro'],
    };
}

