/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Distribuidor } from './Distribuidor';
import {
    DistribuidorFromJSON,
    DistribuidorFromJSONTyped,
    DistribuidorToJSON,
    DistribuidorToJSONTyped,
} from './Distribuidor';
import type { Modelo } from './Modelo';
import {
    ModeloFromJSON,
    ModeloFromJSONTyped,
    ModeloToJSON,
    ModeloToJSONTyped,
} from './Modelo';
import type { Cobros } from './Cobros';
import {
    CobrosFromJSON,
    CobrosFromJSONTyped,
    CobrosToJSON,
    CobrosToJSONTyped,
} from './Cobros';
import type { Seguro } from './Seguro';
import {
    SeguroFromJSON,
    SeguroFromJSONTyped,
    SeguroToJSON,
    SeguroToJSONTyped,
} from './Seguro';

/**
 * 
 * @export
 * @interface Unidad
 */
export interface Unidad {
    /**
     * 
     * @type {number}
     * @memberof Unidad
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof Unidad
     */
    noSerie?: string;
    /**
     * 
     * @type {Modelo}
     * @memberof Unidad
     */
    modelo?: Modelo;
    /**
     * 
     * @type {string}
     * @memberof Unidad
     */
    comentario?: string;
    /**
     * 
     * @type {string}
     * @memberof Unidad
     */
    origen?: string;
    /**
     * 
     * @type {Date}
     * @memberof Unidad
     */
    debisFecha?: Date;
    /**
     * 
     * @type {Distribuidor}
     * @memberof Unidad
     */
    distribuidor?: Distribuidor;
    /**
     * 
     * @type {string}
     * @memberof Unidad
     */
    reportadoA?: string;
    /**
     * 
     * @type {Date}
     * @memberof Unidad
     */
    pagoDistribuidora?: Date;
    /**
     * 
     * @type {number}
     * @memberof Unidad
     */
    valorUnidad?: number;
    /**
     * 
     * @type {Array<Seguro>}
     * @memberof Unidad
     */
    seguros?: Array<Seguro>;
    /**
     * 
     * @type {Array<Cobros>}
     * @memberof Unidad
     */
    cobros?: Array<Cobros>;
}

/**
 * Check if a given object implements the Unidad interface.
 */
export function instanceOfUnidad(value: object): value is Unidad {
    return true;
}

export function UnidadFromJSON(json: any): Unidad {
    return UnidadFromJSONTyped(json, false);
}

export function UnidadFromJSONTyped(json: any, ignoreDiscriminator: boolean): Unidad {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'noSerie': json['noSerie'] == null ? undefined : json['noSerie'],
        'modelo': json['modelo'] == null ? undefined : ModeloFromJSON(json['modelo']),
        'comentario': json['comentario'] == null ? undefined : json['comentario'],
        'origen': json['origen'] == null ? undefined : json['origen'],
        'debisFecha': json['debisFecha'] == null ? undefined : (new Date(json['debisFecha'])),
        'distribuidor': json['distribuidor'] == null ? undefined : DistribuidorFromJSON(json['distribuidor']),
        'reportadoA': json['reportadoA'] == null ? undefined : json['reportadoA'],
        'pagoDistribuidora': json['pagoDistribuidora'] == null ? undefined : (new Date(json['pagoDistribuidora'])),
        'valorUnidad': json['valorUnidad'] == null ? undefined : json['valorUnidad'],
        'seguros': json['seguros'] == null ? undefined : ((json['seguros'] as Array<any>).map(SeguroFromJSON)),
        'cobros': json['cobros'] == null ? undefined : ((json['cobros'] as Array<any>).map(CobrosFromJSON)),
    };
}

export function UnidadToJSON(json: any): Unidad {
    return UnidadToJSONTyped(json, false);
}

export function UnidadToJSONTyped(value?: Unidad | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'noSerie': value['noSerie'],
        'modelo': ModeloToJSON(value['modelo']),
        'comentario': value['comentario'],
        'origen': value['origen'],
        'debisFecha': value['debisFecha'] == null ? undefined : ((value['debisFecha']).toISOString().substring(0,10)),
        'distribuidor': DistribuidorToJSON(value['distribuidor']),
        'reportadoA': value['reportadoA'],
        'pagoDistribuidora': value['pagoDistribuidora'] == null ? undefined : ((value['pagoDistribuidora']).toISOString().substring(0,10)),
        'valorUnidad': value['valorUnidad'],
        'seguros': value['seguros'] == null ? undefined : ((value['seguros'] as Array<any>).map(SeguroToJSON)),
        'cobros': value['cobros'] == null ? undefined : ((value['cobros'] as Array<any>).map(CobrosToJSON)),
    };
}

