/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CrearModeloRequest,
  ModeloDTO,
} from '../models/index';
import {
    CrearModeloRequestFromJSON,
    CrearModeloRequestToJSON,
    ModeloDTOFromJSON,
    ModeloDTOToJSON,
} from '../models/index';

export interface CrearRequest {
    crearModeloRequest: CrearModeloRequest;
}

export interface EliminarRequest {
    id: number;
}

/**
 * 
 */
export class ModeloControllerApi extends runtime.BaseAPI {

    /**
     */
    async crearRaw(requestParameters: CrearRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        if (requestParameters['crearModeloRequest'] == null) {
            throw new runtime.RequiredError(
                'crearModeloRequest',
                'Required parameter "crearModeloRequest" was null or undefined when calling crear().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/modelos`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CrearModeloRequestToJSON(requestParameters['crearModeloRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     */
    async crear(requestParameters: CrearRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.crearRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async eliminarRaw(requestParameters: EliminarRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling eliminar().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/modelos/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     */
    async eliminar(requestParameters: EliminarRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.eliminarRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async listar2Raw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ModeloDTO>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/modelos`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ModeloDTOFromJSON));
    }

    /**
     */
    async listar2(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ModeloDTO>> {
        const response = await this.listar2Raw(initOverrides);
        return await response.value();
    }

}
