/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';

export interface ExportarReporteFinancieroRequest {
    mes: string;
}

/**
 * 
 */
export class ReporteFinancieroControllerApi extends runtime.BaseAPI {

    /**
     */
    async exportarReporteFinancieroRaw(requestParameters: ExportarReporteFinancieroRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['mes'] == null) {
            throw new runtime.RequiredError(
                'mes',
                'Required parameter "mes" was null or undefined when calling exportarReporteFinanciero().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['mes'] != null) {
            queryParameters['mes'] = requestParameters['mes'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/reportes/financiero`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async exportarReporteFinanciero(requestParameters: ExportarReporteFinancieroRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.exportarReporteFinancieroRaw(requestParameters, initOverrides);
    }

}
