stages:
  - build
  - push
  - generate

# 1. CONSTRUCCIÓN DE LA IMAGEN DOCKER
build-docker-image:
  stage: build
  image: docker:24.0.7
  services:
    - docker:24.0.7-dind
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_TLS_CERTDIR: ""
  script:
    - docker build -t robertoruvalcaba/transporte-api:latest .
  only:
    - main

# 2. PUSH A DOCKER HUB
push-docker-image:
  stage: push
  image: docker:24.0.7
  services:
    - docker:24.0.7-dind
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_TLS_CERTDIR: ""
  script:
    - docker login -u "$DOCKER_USER" -p "$DOCKER_PASSWORD"
    - docker push robertoruvalcaba/transporte-api:latest
  only:
    - main

# 3. GENERACIÓN DE LA LIBRERÍA API CLIENT
generate-api-client:
  stage: generate
  image: node:20.17.0
  script:
    - npm install -g @angular/cli@19
    - npm install -g openapi-typescript-codegen
    - git clone https://oauth2:${CI_PUSH_TOKEN}@gitlab.com/projects-dev4/adavec/prefactura-api-client.git api-client
    - cd api-client
    - rm -rf src/app/api
    - npx openapi-typescript-codegen --input https://transporte-api-latest.onrender.com/v3/api-docs --output src/app/api --client axios
    - git config user.email "ci-bot@example.com"
    - git config user.name "CI Bot"
    - git add src/app/api
    - git commit -m "🔁 Auto-generado desde backend commit $CI_COMMIT_SHORT_SHA" || echo "Sin cambios"
    - git push origin main
  only:
    - main