stages:
  - generate

generate-api-client:
  stage: generate
  image: node:20.17.0
  script:
    # Instalar Angular CLI 19 globalmente
    - npm install -g @angular/cli@19
    # Instalar generador de cliente OpenAPI
    - npm install -g openapi-typescript-codegen
    # Clonar el repositorio donde se guarda la librer칤a generada
    - git clone "$API_CLIENT_REPO" api-client
    - cd api-client
    # Limpiar la carpeta generada anteriormente
    - rm -rf src/app/api
    # Generar nueva versi칩n desde tu Swagger p칰blico
    - openapi-typescript-codegen \
        --input https://transporte-api-latest.onrender.com/v3/api-docs \
        --output src/app/api \
        --client axios
    # Configuraci칩n de git para el commit autom치tico
    - git config user.email "ci-bot@example.com"
    - git config user.name "CI Bot"
    - git add src/app/api
    - git commit -m "游대 Auto-generado desde backend commit $CI_COMMIT_SHORT_SHA" || echo "Sin cambios"
    - git push origin main

