image: node:latest

stages:
  - build
  - publish

build:
  stage: build
  script:
    - cd api-angular-client
    - npm ci
    - npm run build
  artifacts:
    paths:
      - api-angular-client/dist/

publish:
  stage: publish
  script:
    - cd api-angular-client
    - npm ci
    - npm run build
    - npm version patch --no-git-tag-version
    - echo "//gitlab.com/api/v4/projects/69304666/packages/npm/:_authToken=${CI_JOB_TOKEN}" > .npmrc
    - npm publish || echo "Ya existe esta versión. Publicación omitida."
  only:
    - main
