/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CobroDTO { 
    id?: number;
    unidadId?: number;
    tarifaUnica?: number;
    cuotaAsociacion?: number;
    fondoEstrella?: number;
    dias?: number;
    fechaTraslado?: string;
}

