/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Unidad } from './unidad';


export interface Cobros { 
    id?: number;
    unidad?: Unidad;
    tarifaUnica?: number;
    cuotaAsociacion?: number;
    fondoEstrella?: number;
    dias?: number;
    fechaTraslado?: string;
}

