/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CrearDistribuidorDTO { 
    nombreDistribuidora?: string;
    claveDistribuidora?: string;
    contacto?: string;
    telefono?: number;
    extension?: number;
    correo?: string;
    sucursal?: string;
}

