/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CrearUnidadRequest { 
    noSerie?: string;
    comentario?: string;
    origen?: string;
    debisFecha?: string;
    reportadoA?: string;
    pagoDistribuidora?: string;
    valorUnidad?: number;
    modeloId?: number;
    distribuidorId?: number;
}

