/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Unidad } from './unidad';


export interface Distribuidor { 
    id?: number;
    nombreDistribuidora?: string;
    claveDistribuidora?: string;
    contacto?: string;
    telefono?: number;
    extension?: number;
    correo?: string;
    sucursal?: string;
    unidades?: Array<Unidad>;
}

