/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Distribuidor } from './distribuidor';
import { Unidad } from './unidad';


export interface Seguro { 
    id?: number;
    distribuidor?: Distribuidor;
    unidad?: Unidad;
    factura?: string;
    valorSeguro?: number;
    seguroDistribuidor?: number;
    cuotaSeguro?: number;
}

