/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Distribuidor } from './distribuidor';
import { Modelo } from './modelo';
import { Cobros } from './cobros';
import { Seguro } from './seguro';


export interface Unidad { 
    id?: number;
    noSerie?: string;
    modelo?: Modelo;
    comentario?: string;
    origen?: string;
    debisFecha?: string;
    distribuidor?: Distribuidor;
    reportadoA?: string;
    pagoDistribuidora?: string;
    valorUnidad?: number;
    seguros?: Array<Seguro>;
    cobros?: Array<Cobros>;
}

