/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DistribuidoraInfoDTO } from './distribuidoraInfoDTO';
import { ModeloDTO } from './modeloDTO';
import { SeguroResumenDTO } from './seguroResumenDTO';


export interface UnidadDTO { 
    id?: number;
    noSerie?: string;
    comentario?: string;
    origen?: string;
    debisFecha?: string;
    reportadoA?: string;
    pagoDistribuidora?: string;
    valorUnidad?: number;
    modelo?: ModeloDTO;
    distribuidor?: DistribuidoraInfoDTO;
    seguro?: SeguroResumenDTO;
}

