image: node:latest

stages:
  - build
  - publish

before_script:
  - npm ci

build:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - dist/

publish:
  stage: publish
  script:
    - echo "//gitlab.com/api/v4/projects/69304666/packages/npm/:_authToken=${CI_JOB_TOKEN}" > .npmrc
    - npm publish
  only:
    - main
