/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ImportarDesdeTxtRequest,
} from '../models/index';
import {
    ImportarDesdeTxtRequestFromJSON,
    ImportarDesdeTxtRequestToJSON,
} from '../models/index';

export interface ImportarDesdeTxtOperationRequest {
    importarDesdeTxtRequest?: ImportarDesdeTxtRequest;
}

/**
 * 
 */
export class TxtImportControllerApi extends runtime.BaseAPI {

    /**
     */
    async importarDesdeTxtRaw(requestParameters: ImportarDesdeTxtOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/importar/txt`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ImportarDesdeTxtRequestToJSON(requestParameters['importarDesdeTxtRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     */
    async importarDesdeTxt(requestParameters: ImportarDesdeTxtOperationRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.importarDesdeTxtRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
