/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CrearSeguroRequest
 */
export interface CrearSeguroRequest {
    /**
     * 
     * @type {string}
     * @memberof CrearSeguroRequest
     */
    factura?: string;
    /**
     * 
     * @type {number}
     * @memberof CrearSeguroRequest
     */
    valorSeguro?: number;
    /**
     * 
     * @type {number}
     * @memberof CrearSeguroRequest
     */
    seguroDistribuidor?: number;
    /**
     * 
     * @type {number}
     * @memberof CrearSeguroRequest
     */
    unidadId?: number;
}

/**
 * Check if a given object implements the CrearSeguroRequest interface.
 */
export function instanceOfCrearSeguroRequest(value: object): value is CrearSeguroRequest {
    return true;
}

export function CrearSeguroRequestFromJSON(json: any): CrearSeguroRequest {
    return CrearSeguroRequestFromJSONTyped(json, false);
}

export function CrearSeguroRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CrearSeguroRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'factura': json['factura'] == null ? undefined : json['factura'],
        'valorSeguro': json['valorSeguro'] == null ? undefined : json['valorSeguro'],
        'seguroDistribuidor': json['seguroDistribuidor'] == null ? undefined : json['seguroDistribuidor'],
        'unidadId': json['unidadId'] == null ? undefined : json['unidadId'],
    };
}

export function CrearSeguroRequestToJSON(json: any): CrearSeguroRequest {
    return CrearSeguroRequestToJSONTyped(json, false);
}

export function CrearSeguroRequestToJSONTyped(value?: CrearSeguroRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'factura': value['factura'],
        'valorSeguro': value['valorSeguro'],
        'seguroDistribuidor': value['seguroDistribuidor'],
        'unidadId': value['unidadId'],
    };
}

