/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CrearDistribuidorDTO
 */
export interface CrearDistribuidorDTO {
    /**
     * 
     * @type {string}
     * @memberof CrearDistribuidorDTO
     */
    nombreDistribuidora?: string;
    /**
     * 
     * @type {string}
     * @memberof CrearDistribuidorDTO
     */
    claveDistribuidora?: string;
    /**
     * 
     * @type {string}
     * @memberof CrearDistribuidorDTO
     */
    contacto?: string;
    /**
     * 
     * @type {number}
     * @memberof CrearDistribuidorDTO
     */
    telefono?: number;
    /**
     * 
     * @type {number}
     * @memberof CrearDistribuidorDTO
     */
    extension?: number;
    /**
     * 
     * @type {string}
     * @memberof CrearDistribuidorDTO
     */
    correo?: string;
    /**
     * 
     * @type {string}
     * @memberof CrearDistribuidorDTO
     */
    sucursal?: string;
}

/**
 * Check if a given object implements the CrearDistribuidorDTO interface.
 */
export function instanceOfCrearDistribuidorDTO(value: object): value is CrearDistribuidorDTO {
    return true;
}

export function CrearDistribuidorDTOFromJSON(json: any): CrearDistribuidorDTO {
    return CrearDistribuidorDTOFromJSONTyped(json, false);
}

export function CrearDistribuidorDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): CrearDistribuidorDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'nombreDistribuidora': json['nombreDistribuidora'] == null ? undefined : json['nombreDistribuidora'],
        'claveDistribuidora': json['claveDistribuidora'] == null ? undefined : json['claveDistribuidora'],
        'contacto': json['contacto'] == null ? undefined : json['contacto'],
        'telefono': json['telefono'] == null ? undefined : json['telefono'],
        'extension': json['extension'] == null ? undefined : json['extension'],
        'correo': json['correo'] == null ? undefined : json['correo'],
        'sucursal': json['sucursal'] == null ? undefined : json['sucursal'],
    };
}

export function CrearDistribuidorDTOToJSON(json: any): CrearDistribuidorDTO {
    return CrearDistribuidorDTOToJSONTyped(json, false);
}

export function CrearDistribuidorDTOToJSONTyped(value?: CrearDistribuidorDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'nombreDistribuidora': value['nombreDistribuidora'],
        'claveDistribuidora': value['claveDistribuidora'],
        'contacto': value['contacto'],
        'telefono': value['telefono'],
        'extension': value['extension'],
        'correo': value['correo'],
        'sucursal': value['sucursal'],
    };
}

