/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CrearCobroRequest
 */
export interface CrearCobroRequest {
    /**
     * 
     * @type {number}
     * @memberof CrearCobroRequest
     */
    unidadId?: number;
    /**
     * 
     * @type {number}
     * @memberof CrearCobroRequest
     */
    tarifaUnica?: number;
    /**
     * 
     * @type {number}
     * @memberof CrearCobroRequest
     */
    cuotaAsociacion?: number;
    /**
     * 
     * @type {number}
     * @memberof CrearCobroRequest
     */
    fondoEstrella?: number;
    /**
     * 
     * @type {number}
     * @memberof CrearCobroRequest
     */
    dias?: number;
    /**
     * 
     * @type {string}
     * @memberof CrearCobroRequest
     */
    fechaTraslado?: string;
}

/**
 * Check if a given object implements the CrearCobroRequest interface.
 */
export function instanceOfCrearCobroRequest(value: object): value is CrearCobroRequest {
    return true;
}

export function CrearCobroRequestFromJSON(json: any): CrearCobroRequest {
    return CrearCobroRequestFromJSONTyped(json, false);
}

export function CrearCobroRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CrearCobroRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'unidadId': json['unidadId'] == null ? undefined : json['unidadId'],
        'tarifaUnica': json['tarifaUnica'] == null ? undefined : json['tarifaUnica'],
        'cuotaAsociacion': json['cuotaAsociacion'] == null ? undefined : json['cuotaAsociacion'],
        'fondoEstrella': json['fondoEstrella'] == null ? undefined : json['fondoEstrella'],
        'dias': json['dias'] == null ? undefined : json['dias'],
        'fechaTraslado': json['fechaTraslado'] == null ? undefined : json['fechaTraslado'],
    };
}

export function CrearCobroRequestToJSON(json: any): CrearCobroRequest {
    return CrearCobroRequestToJSONTyped(json, false);
}

export function CrearCobroRequestToJSONTyped(value?: CrearCobroRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'unidadId': value['unidadId'],
        'tarifaUnica': value['tarifaUnica'],
        'cuotaAsociacion': value['cuotaAsociacion'],
        'fondoEstrella': value['fondoEstrella'],
        'dias': value['dias'],
        'fechaTraslado': value['fechaTraslado'],
    };
}

