/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ImportarDesdeTxtRequest
 */
export interface ImportarDesdeTxtRequest {
    /**
     * 
     * @type {Blob}
     * @memberof ImportarDesdeTxtRequest
     */
    archivo: Blob;
}

/**
 * Check if a given object implements the ImportarDesdeTxtRequest interface.
 */
export function instanceOfImportarDesdeTxtRequest(value: object): value is ImportarDesdeTxtRequest {
    if (!('archivo' in value) || value['archivo'] === undefined) return false;
    return true;
}

export function ImportarDesdeTxtRequestFromJSON(json: any): ImportarDesdeTxtRequest {
    return ImportarDesdeTxtRequestFromJSONTyped(json, false);
}

export function ImportarDesdeTxtRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImportarDesdeTxtRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'archivo': json['archivo'],
    };
}

export function ImportarDesdeTxtRequestToJSON(json: any): ImportarDesdeTxtRequest {
    return ImportarDesdeTxtRequestToJSONTyped(json, false);
}

export function ImportarDesdeTxtRequestToJSONTyped(value?: ImportarDesdeTxtRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'archivo': value['archivo'],
    };
}

