/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Modelo
 */
export interface Modelo {
    /**
     * 
     * @type {number}
     * @memberof Modelo
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof Modelo
     */
    nombre?: string;
    /**
     * 
     * @type {string}
     * @memberof Modelo
     */
    uso?: string;
}

/**
 * Check if a given object implements the Modelo interface.
 */
export function instanceOfModelo(value: object): value is Modelo {
    return true;
}

export function ModeloFromJSON(json: any): Modelo {
    return ModeloFromJSONTyped(json, false);
}

export function ModeloFromJSONTyped(json: any, ignoreDiscriminator: boolean): Modelo {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'nombre': json['nombre'] == null ? undefined : json['nombre'],
        'uso': json['uso'] == null ? undefined : json['uso'],
    };
}

export function ModeloToJSON(json: any): Modelo {
    return ModeloToJSONTyped(json, false);
}

export function ModeloToJSONTyped(value?: Modelo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'nombre': value['nombre'],
        'uso': value['uso'],
    };
}

