/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SeguroResumenDTO
 */
export interface SeguroResumenDTO {
    /**
     * 
     * @type {string}
     * @memberof SeguroResumenDTO
     */
    factura?: string;
    /**
     * 
     * @type {number}
     * @memberof SeguroResumenDTO
     */
    valorSeguro?: number;
    /**
     * 
     * @type {number}
     * @memberof SeguroResumenDTO
     */
    seguroDistribuidor?: number;
}

/**
 * Check if a given object implements the SeguroResumenDTO interface.
 */
export function instanceOfSeguroResumenDTO(value: object): value is SeguroResumenDTO {
    return true;
}

export function SeguroResumenDTOFromJSON(json: any): SeguroResumenDTO {
    return SeguroResumenDTOFromJSONTyped(json, false);
}

export function SeguroResumenDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): SeguroResumenDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'factura': json['factura'] == null ? undefined : json['factura'],
        'valorSeguro': json['valorSeguro'] == null ? undefined : json['valorSeguro'],
        'seguroDistribuidor': json['seguroDistribuidor'] == null ? undefined : json['seguroDistribuidor'],
    };
}

export function SeguroResumenDTOToJSON(json: any): SeguroResumenDTO {
    return SeguroResumenDTOToJSONTyped(json, false);
}

export function SeguroResumenDTOToJSONTyped(value?: SeguroResumenDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'factura': value['factura'],
        'valorSeguro': value['valorSeguro'],
        'seguroDistribuidor': value['seguroDistribuidor'],
    };
}

