/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DistribuidoraInfoDTO } from './DistribuidoraInfoDTO';
import {
    DistribuidoraInfoDTOFromJSON,
    DistribuidoraInfoDTOFromJSONTyped,
    DistribuidoraInfoDTOToJSON,
    DistribuidoraInfoDTOToJSONTyped,
} from './DistribuidoraInfoDTO';
import type { ModeloDTO } from './ModeloDTO';
import {
    ModeloDTOFromJSON,
    ModeloDTOFromJSONTyped,
    ModeloDTOToJSON,
    ModeloDTOToJSONTyped,
} from './ModeloDTO';
import type { SeguroResumenDTO } from './SeguroResumenDTO';
import {
    SeguroResumenDTOFromJSON,
    SeguroResumenDTOFromJSONTyped,
    SeguroResumenDTOToJSON,
    SeguroResumenDTOToJSONTyped,
} from './SeguroResumenDTO';

/**
 * 
 * @export
 * @interface UnidadDTO
 */
export interface UnidadDTO {
    /**
     * 
     * @type {number}
     * @memberof UnidadDTO
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof UnidadDTO
     */
    noSerie?: string;
    /**
     * 
     * @type {string}
     * @memberof UnidadDTO
     */
    comentario?: string;
    /**
     * 
     * @type {string}
     * @memberof UnidadDTO
     */
    origen?: string;
    /**
     * 
     * @type {string}
     * @memberof UnidadDTO
     */
    debisFecha?: string;
    /**
     * 
     * @type {string}
     * @memberof UnidadDTO
     */
    reportadoA?: string;
    /**
     * 
     * @type {string}
     * @memberof UnidadDTO
     */
    pagoDistribuidora?: string;
    /**
     * 
     * @type {number}
     * @memberof UnidadDTO
     */
    valorUnidad?: number;
    /**
     * 
     * @type {ModeloDTO}
     * @memberof UnidadDTO
     */
    modelo?: ModeloDTO;
    /**
     * 
     * @type {DistribuidoraInfoDTO}
     * @memberof UnidadDTO
     */
    distribuidor?: DistribuidoraInfoDTO;
    /**
     * 
     * @type {SeguroResumenDTO}
     * @memberof UnidadDTO
     */
    seguro?: SeguroResumenDTO;
}

/**
 * Check if a given object implements the UnidadDTO interface.
 */
export function instanceOfUnidadDTO(value: object): value is UnidadDTO {
    return true;
}

export function UnidadDTOFromJSON(json: any): UnidadDTO {
    return UnidadDTOFromJSONTyped(json, false);
}

export function UnidadDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): UnidadDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'noSerie': json['noSerie'] == null ? undefined : json['noSerie'],
        'comentario': json['comentario'] == null ? undefined : json['comentario'],
        'origen': json['origen'] == null ? undefined : json['origen'],
        'debisFecha': json['debisFecha'] == null ? undefined : json['debisFecha'],
        'reportadoA': json['reportadoA'] == null ? undefined : json['reportadoA'],
        'pagoDistribuidora': json['pagoDistribuidora'] == null ? undefined : json['pagoDistribuidora'],
        'valorUnidad': json['valorUnidad'] == null ? undefined : json['valorUnidad'],
        'modelo': json['modelo'] == null ? undefined : ModeloDTOFromJSON(json['modelo']),
        'distribuidor': json['distribuidor'] == null ? undefined : DistribuidoraInfoDTOFromJSON(json['distribuidor']),
        'seguro': json['seguro'] == null ? undefined : SeguroResumenDTOFromJSON(json['seguro']),
    };
}

export function UnidadDTOToJSON(json: any): UnidadDTO {
    return UnidadDTOToJSONTyped(json, false);
}

export function UnidadDTOToJSONTyped(value?: UnidadDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'noSerie': value['noSerie'],
        'comentario': value['comentario'],
        'origen': value['origen'],
        'debisFecha': value['debisFecha'],
        'reportadoA': value['reportadoA'],
        'pagoDistribuidora': value['pagoDistribuidora'],
        'valorUnidad': value['valorUnidad'],
        'modelo': ModeloDTOToJSON(value['modelo']),
        'distribuidor': DistribuidoraInfoDTOToJSON(value['distribuidor']),
        'seguro': SeguroResumenDTOToJSON(value['seguro']),
    };
}

